apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-greencity-ubs
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-greencity-ubs
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-greencity-ubs
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: {{ .Release.Name }}-greencity-ubs
        image: {{ .Values.deployment.image }}
        resources:
          requests:
            cpu: {{ .Values.deployment.requests.cpu }}
            memory: {{ .Values.deployment.requests.memory }}
          limits:
            cpu: {{ .Values.deployment.limits.cpu }}
            memory: {{ .Values.deployment.limits.memory }}  
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: API-KEY

        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: API-SECRET

        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: APPLICATIONINSIGHTS-CONNECTION-STRING

        - name: AZURE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: AZURE-CONNECTION-STRING

        - name: AZURE_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: AZURE-CONTAINER-NAME

        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: BUCKET-NAME

        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: DATABASE-PASSWORD

        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: DATABASE-USER

        # - name: DATASOURCE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Values.externalSecret.secretName }}
        #       key: API-KEY

        - name: DIALECT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: DIALECT

        - name: DRIVER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: DRIVER

        # - name: EMAIL_TOPIC
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Values.externalSecret.secretName }}
        #       key: EMAIL-TOPIC

        - name: GREENCITYUSER_SERVER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: GREENCITYUSER-SERVER-ADDRESS

        - name: HIBERNATE_CONFIG
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: HIBERNATE-CONFIG

        - name: JAWSDB_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: {{ if eq .Values.environment "prod" }}JAWSDB-URL-UBS{{ else }}JAWSDB-URL-UBS-TEST{{ end }}

        - name: JDBC_LOB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: JDBC-LOB

        - name: LIQUIBASE_ENABLE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LIQUIBASE-ENABLE

        - name: LIQUIBASE_LOG
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LIQUIBASE-LOG

        # - name: MAX_FILE_SIZE
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Values.externalSecret.secretName }}
        #       key: API-KEY

        - name: POOL_SIZE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: POOL-SIZE

        - name: SHOW_SQL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: SHOW-SQL

        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: SPRING-PROFILES-ACTIVE

        - name: TOKEN_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: TOKEN-KEY

        - name: MERCHANT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: MERCHANT-ID

        - name: LIQPAY_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LIQPAY-PUBLIC-KEY

        - name: LIQPAY_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LIQPAY-PRIVATE-KEY

        - name: FONDY_PAYMENT_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: FONDY-PAYMENT-KEY

        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: TELEGRAM-BOT-TOKEN

        - name: TELEGRAM_BOT_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: TELEGRAM-BOT-NAME

        - name: VIBER_BOT_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: VIBER-BOT-URL

        - name: VIBER_BOT_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: VIBER-BOT-URI

        - name: VIBER_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: VIBER-BOT-TOKEN

        - name: FONDY_REDIRECT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: FONDY-REDIRECT

        - name: FONDY_PERSONAL_CABINET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: FONDY-PERSONAL-CABINET

        - name: LIQPAY_REDIRECT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LIQPAY-REDIRECT

        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: GOOGLE-API-KEY
        ports:
        - containerPort: 8060
          name: tomcat