apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubs-greencity-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  tls:
  - hosts:
    - greencity-ubs.testgreencity.ga
    secretName: greencity-ubs
  rules:
  - host: greencity-ubs.testgreencity.ga
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: ubs-greencity-service
            port: 
              number: 80