apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-greencity-service-ubs
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8060
  selector:
    app: {{ .Release.Name }}-greencity-ubs