package greencity.enums;

public enum NotificationType {
    UNPAID_ORDER,
    ORDER_IS_PAID,
    COURIER_ITINERARY_FORMED,
    UNPAID_PACKAGE,
    ACCRUED_BONUSES_TO_ACCOUNT,
    VIOLATION_THE_RULES,
    CANCELED_VIOLATION_THE_RULES_BY_THE_MANAGER,
    CHANGED_IN_RULE_VIOLATION_STATUS,
    LETS_STAY_CONNECTED,
    TEST,
    BONUSES_FROM_CANCELLED_ORDER,
    ORDER_STATUS_CHANGED,
    HALF_PAID_ORDER_WITH_STATUS_BROUGHT_BY_HIMSELF,
    DONE_OR_CANCELED_UNPAID_ORDER,
    CUSTOM,
    TARIFF_PRICE_WAS_CHANGED,
    CREATE_NEW_ORDER
}