package greencity.enums;

public enum NotificationType {
    UNPAID_ORDER,
    ORDER_IS_PAID,
    COURIER_ITINERARY_FORMED,
    UNPAID_PACKAGE,
    ACCRUED_BONUSES_TO_ACCOUNT,
    VIOLATION_THE_RULES,
    LETS_STAY_CONNECTED,
    TEST,
    BONUSES_FROM_CANCELLED_ORDER,
    ORDER_BROUGHT_BY_HIMSELF
}