environment: prod

deployment:
  replicas: 1
  image: skyere/greencityubs:latest
  requests:
    cpu: 10m
    memory: 250Mi
  limits:
    cpu: 2
    memory: 1024Mi

externalSecret:
  secretName: greencity-secret

service:
  type: ClusterIP

# You need Nginx ingress controller and cert manager already installed
# https://kubernetes.github.io/ingress-nginx/deploy/
# https://cert-manager.io/docs/installation/helm/#3-install-customresourcedefinitions
ingress:
  hostname: www.pick-up.city
  
