# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.internal.JCacheRegionFactory
spring.jpa.properties.hibernate.javax.cache.uri=classpath:ehcache.xml
spring.jpa.properties.hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider

#RestTemplate
greencity.redirect.user-server-address=http://localhost:8060

#WebClient
webclient.connection-timeout-millis=5000
webclient.response-timeout-millis=5000

# Token expiration time
greencity.authorization.token-key=12312312312312312312312312312312312

#TelegraBot
telegrambots.enabled = false
greencity.bots.ubs-bot-name=mocked
greencity.bots.ubs-bot-token=mocked

#WayForPay
greencity.wayforpay.login=${WAY_FOR_PAY_LOGIN}
greencity.wayforpay.secret=${WAY_FOR_PAY_SECRET}
greencity.wayforpay.merchant.domain.name=${DOMAIN_NAME}

#Payment redirection
greencity.redirect.result-way-for-pay-url=${WAY_FOR_PAY_REDIRECT}
#WayForPay handler redirect
greencity.redirect.green-city-client=${WAY_FOR_PAY_RETURN_URL}
#GreenCityConfirmPage
redirect.confirm-page=${WAY_FOR_PAY_CONFIRM_PAGE}

#OrderLockDuration
order.lock.duration.minutes=5

#Link in telegram notification
greencity.ubs.admin.base-url=${GREENCITY_UBS_ADMIN_BASE_URL}

#Cache
greencity.cache.lifetime=${CACHE_LIFE_TIME:10}

# QuartzProperties
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.jdbc.schema=classpath:db/changelog/logs/ch-add-quartz-tables.xml
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.scheduler.instanceName=MyClusteredScheduler