# Datasource
spring.datasource.url=${DATASOURCE_URL_UBS}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8050

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.internal.JCacheRegionFactory
spring.jpa.properties.hibernate.javax.cache.uri=classpath:ehcache.xml
spring.jpa.properties.hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.jpa.properties.hibernate.default_batch_fetch_size=10

# Liquibase
spring.liquibase.url=${DATASOURCE_URL_UBS}
spring.liquibase.user=${DATASOURCE_USER}
spring.liquibase.password=${DATASOURCE_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#RestTemplate
greencity.redirect.user-server-address=http://localhost:8060

#WebClient
webclient.connection-timeout-millis=5000
webclient.response-timeout-millis=5000

# Token expiration time
greencity.authorization.token-key=123123123123123123123123123123123123

#TelegramBot
greencity.bots.ubs-bot-name=${TELEGRAM_BOT_NAME}
greencity.bots.ubs-bot-token=${TELEGRAM_BOT_TOKEN}

#WayForPay
greencity.wayforpay.login=${WAY_FOR_PAY_LOGIN}
greencity.wayforpay.secret=${WAY_FOR_PAY_SECRET}
greencity.wayforpay.merchant.domain.name=${DOMAIN_NAME}

#Payment redirection
greencity.redirect.result-way-for-pay-url=${WAY_FOR_PAY_REDIRECT}
#WayForPay handler redirect
greencity.redirect.green-city-client=${WAY_FOR_PAY_RETURN_URL}
#GreenCityConfirmPage
redirect.confirm-page=${WAY_FOR_PAY_CONFIRM_PAGE}

#Unpaid order link
greencity.internal.order-url=https://localhost:4200/#/ubs/order/

#OrderLockDuration
order.lock.duration.minutes=5

#Cache
greencity.cache.lifetime=${CACHE_LIFE_TIME:10}
greencity.cache.countQueryCacheLifetime=${COUNT_QUERY_CACHE_LIFE_TIME:10}
greencity.cache.countQueryCacheMaximumEntries=${COUNT_QUERY_CACHE_MAXIMUM_ENTRIES:100}

# Logger
logging.level.root=info
logging.level.io.swagger.models.parameters.AbstractSerializableParameter=ERROR
logging.level.greencity.exception.handler.CustomExceptionHandler=trace
logging.pattern.console=%d{"yyyy/MM/dd HH:mm:ss,SSS"} %magenta([%thread]) %highlight(%-5level) %M\\(%F:%L\\) - %msg%n

# QuartzProperties
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.jdbc.schema=classpath:db/changelog/logs/ch-add-quartz-tables.xml
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.scheduler.instanceName=MyClusteredScheduler