spring.cloud.azure.keyvault.secret.property-source-enabled=false

# Logger
logging.level.root=debug
logging.level.greencity.exception.handler.CustomExceptionHandler=ERROR
logging.file.path=logs
logging.file.name=log.log

spring.datasource.hikari.maximum-pool-size=10

spring.liquibase.enabled=false
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false

greencity.authorization.token-key=12121212121212121212121212

order.lock.duration.minutes=5

webclient.connection-timeout-millis=5000
webclient.response-timeout-millis=5000

greencity.authorization.googleApiKey=fake-google-key

greencity.bots.ubs-bot-name=fake-bot-name
greencity.bots.ubs-bot-token=fake-bot-token
greencity.bots.ubs-bot-ui=fake-ubs-bot-ui

greencity.wayforpay.merchant.domain.name=fake-domain-name
greencity.redirect.result-way-for-pay-url=fake-url
greencity.wayforpay.login=fake-login
greencity.wayforpay.secret=fake-secret
greencity.redirect.green-city-client=fake-green-city-client

greencity.sing-in.secret-token=fake-secret-token

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB

spring.quartz.auto-startup=false

